# Generated by Django 5.2.13 on 2026-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_footage_reels', '0002_refactor_reel_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelrenderjob',
            name='status',
            field=models.CharField(default='queued', max_length=32),
        ),
    ]
