# Generated by Django 5.2.13 on 2026-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_footage_reels', '0003_alter_reelrenderjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelStockVideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(db_index=True, max_length=128)),
                ('run_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('listing_title', models.CharField(blank=True, max_length=255)),
                ('listing_price', models.CharField(blank=True, max_length=128)),
                ('video_script', models.TextField(blank=True)),
                ('final_reel_url', models.TextField(blank=True)),
                ('preview_reel_url', models.TextField(blank=True)),
                ('thumbnail_image_url', models.TextField(blank=True)),
                ('thumbnail_object_key', models.CharField(blank=True, max_length=1024)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
